// The API payloads are intentionally dynamic because the local SQLite schema is migrated in place.
// Runtime validation happens at the FastAPI boundary; keep the UI resilient to compatibility columns.
// @ts-nocheck
import { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BarChart3, Bell, Calculator, CheckSquare, ChevronRight, ClipboardList, Columns3, FileSpreadsheet, FolderKanban, LayoutDashboard, Menu, MessageSquareText, Moon, Plus, Search, Settings2, Sun, X } from 'lucide-react';
import './styles.css';

type Proposal = Record<string, any>;
type Stage = { id:number; nome:string; ativo:number; ordem:number };
const api = async <T,>(path:string, init?:RequestInit):Promise<T> => {
  const response=await fetch(`/api${path}`, {headers:{'Content-Type':'application/json', ...(init?.headers||{})},...init});
  if(!response.ok) throw new Error((await response.text()) || 'Não foi possível concluir a operação');
  return response.status===204 ? undefined as T : response.json();
};
const money=(value:any)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(value||0));
const today=new Date().toISOString().slice(0,10);

const navigation=[['funil','Funil',Columns3],['propostas','Propostas',ClipboardList],['nova','Nova proposta',Plus],['hoje','Hoje',CheckSquare],['tarefas','Agenda',CheckSquare],['simulador','Simulador INSS',Calculator],['mensagens','Mensagens',MessageSquareText],['encerradas','Encerradas',FolderKanban],['dashboard','Dashboard',BarChart3],['configuracoes','Etapas',Settings2],['importar','Importar/Exportar',FileSpreadsheet]] as const;

function App(){
  const [page,setPage]=useState('funil'); const [dark,setDark]=useState(localStorage.theme==='dark'); const [drawer,setDrawer]=useState(false); const [search,setSearch]=useState('');
  useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';localStorage.theme=dark?'dark':'light'},[dark]);
  return <div className="shell"><aside className={drawer?'sidebar open':'sidebar'}><div className="brand"><span>CC</span><div><b>CRM Consig</b><small>Next · local</small></div><button className="mobile-only icon" onClick={()=>setDrawer(false)}><X/></button></div><nav>{navigation.map(([key,label,Icon])=><button key={key} className={page===key?'active':''} onClick={()=>{setPage(key);setDrawer(false)}}><Icon size={18}/>{label}</button>)}</nav><div className="sidebar-footer">Dados em cópia local<br/>do CRM original</div></aside><main><header><button className="mobile-only icon" onClick={()=>setDrawer(true)}><Menu/></button><div className="global-search"><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Pesquisar cliente, CPF ou telefone..."/><kbd>⌘ K</kbd></div><button className="icon" title="Notificações"><Bell size={19}/></button><button className="icon" onClick={()=>setDark(!dark)}>{dark?<Sun size={19}/>:<Moon size={19}/>}</button><button className="primary" onClick={()=>setPage('nova')}><Plus size={18}/>Nova proposta</button></header><section className="content">{page==='funil'&&<Board search={search}/>} {page==='propostas'&&<Proposals search={search} onNew={()=>setPage('nova')}/>} {page==='nova'&&<ProposalForm onDone={()=>setPage('propostas')}/>} {page==='hoje'&&<Today/>} {page==='tarefas'&&<Tasks/>} {page==='simulador'&&<Simulator/>} {page==='mensagens'&&<Messages/>} {page==='encerradas'&&<Closed/>} {page==='dashboard'&&<Dashboard/>} {page==='configuracoes'&&<Stages/>} {page==='importar'&&<ImportExport/>}</section></main></div>
}

function Title({title,subtitle,action}:{title:string;subtitle:string;action?:React.ReactNode}){return <div className="title"><div><h1>{title}</h1><p>{subtitle}</p></div>{action}</div>}
function Board({search}:{search:string}){const [data,setData]=useState<{stages:Stage[],columns:Record<string,Proposal[]>}>({stages:[],columns:{}}); const [detail,setDetail]=useState<Proposal|null>(null); const load=()=>api<typeof data>('/board').then(setData); useEffect(()=>{void load()},[]); const update=async(id:number,status:string)=>{await api(`/proposals/${id}/status`,{method:'POST',body:JSON.stringify({status})});void load()}; const stages=data.stages.filter(x=>x.ativo); return <><Title title="Funil de propostas" subtitle="Arraste ou mova as propostas entre as etapas."/><div className="board">{stages.map(stage=>{const items=(data.columns[stage.nome]||[]).filter(p=>!search||`${p.nome} ${p.cpf} ${p.telefone}`.toLowerCase().includes(search.toLowerCase()));return <section className="column" key={stage.id} onDragOver={e=>e.preventDefault()} onDrop={e=>update(+e.dataTransfer.getData('id'),stage.nome)}><div className="column-title"><b>{stage.nome}</b><span>{items.length}</span></div><small>{money(items.reduce((n,p)=>n+Number(p.comissao||0),0))} comissão</small><div className="cards">{items.map(p=><article key={p.id} draggable onDragStart={e=>e.dataTransfer.setData('id',p.id)} onClick={()=>setDetail(p)}><strong>{p.nome}</strong><small>{p.produto||'Sem produto'} · {p.banco_digitado||p.banco_atual||'Sem banco'}</small><div><span>{p.cpf||'CPF não informado'}</span><b>{money(p.troco)}</b></div></article>)}{!items.length&&<div className="empty">Sem propostas</div>}</div></section>})}</div>{detail&&<ProposalDrawer proposal={detail} stages={stages} onClose={()=>setDetail(null)} onChanged={load}/>}</>}
function Proposals({search,onNew}:{search:string;onNew:()=>void}){const [data,setData]=useState<{items:Proposal[],total:number}>({items:[],total:0});const [filters,setFilters]=useState({q:search,status:'',mes:''}); const [detail,setDetail]=useState<Proposal|null>(null); const load=()=>api<typeof data>('/proposals?'+new URLSearchParams(filters)).then(setData);useEffect(()=>{void load()},[filters.q,filters.status,filters.mes]);useEffect(()=>setFilters(x=>({...x,q:search})),[search]); return <><Title title="Propostas" subtitle={`${data.total} registros encontrados`} action={<button className="primary" onClick={onNew}><Plus size={17}/>Nova proposta</button>}/><div className="filters"><input placeholder="Nome, CPF, telefone ou número" value={filters.q} onChange={e=>setFilters({...filters,q:e.target.value})}/><select value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">Todos os status</option><option>Pago</option><option>Perdido / Cancelado</option></select><input type="month" value={filters.mes} onChange={e=>setFilters({...filters,mes:e.target.value})}/></div><div className="table-wrap"><table><thead><tr><th>Cliente</th><th>Produto</th><th>Banco digitado</th><th>Status</th><th>Troco</th><th>Atualização</th></tr></thead><tbody>{data.items.map(p=><tr key={p.id} onClick={()=>setDetail(p)}><td><b>{p.nome}</b><small>{p.cpf}</small></td><td>{p.produto}</td><td>{p.banco_digitado}</td><td><span className="badge">{p.status}</span></td><td>{money(p.troco)}</td><td>{String(p.data_atualizacao||'').slice(0,10)}</td></tr>)}</tbody></table></div>{detail&&<ProposalDrawer proposal={detail} stages={[]} onClose={()=>setDetail(null)} onChanged={load}/>}</>}
function ProposalForm({onDone}:{onDone:()=>void}){const [form,setForm]=useState<Record<string,string>>({nome:'',cpf:'',nb_matricula:'',produto:'Portabilidade',telefone:'',tipo_cliente:'INSS',banco_atual:'',banco_digitado:'',promotora:'',troco:'',parcela_atual:'',nova_parcela:'',observacoes:''});const [saving,setSaving]=useState(false); const set=(key:string,value:string)=>setForm({...form,[key]:value}); const submit=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);try{await api('/proposals',{method:'POST',body:JSON.stringify({values:form})});onDone()}finally{setSaving(false)}}; return <><Title title="Nova proposta" subtitle="Cadastro rápido, salvo automaticamente em Aguardando inserção."/><form className="form card" onSubmit={submit}><h2>Dados do cliente</h2><div className="grid">{[['nome','Nome completo *'],['cpf','CPF *'],['nb_matricula','NB / matrícula *'],['telefone','Telefone *'],['tipo_cliente','Tipo de cliente'],['produto','Produto'],['banco_atual','Banco atual'],['banco_digitado','Banco digitado'],['promotora','Promotora'],['troco','Valor / troco'],['parcela_atual','Parcela atual'],['nova_parcela','Nova parcela']].map(([key,label])=><label key={key}>{label}<input required={key==='nome'||key==='cpf'||key==='nb_matricula'||key==='telefone'} value={form[key]||''} onChange={e=>set(key,e.target.value)}/></label>)}</div><label>Observações<textarea value={form.observacoes} onChange={e=>set('observacoes',e.target.value)}/></label><div className="actions"><button className="primary" disabled={saving}>{saving?'Salvando...':'Salvar em Aguardando inserção'}</button><button type="button" onClick={onDone}>Cancelar</button></div></form></>}
function ProposalDrawer({proposal,stages,onClose,onChanged}:{proposal:Proposal;stages:Stage[];onClose:()=>void;onChanged:()=>void}){const [full,setFull]=useState<Proposal|null>(null);const [note,setNote]=useState('');useEffect(()=>{api<Proposal>(`/proposals/${proposal.id}`).then(setFull)},[proposal.id]);const p=full||proposal;const status=async(value:string)=>{await api(`/proposals/${p.id}/status`,{method:'POST',body:JSON.stringify({status:value})});onChanged();api<Proposal>(`/proposals/${p.id}`).then(setFull)}; const add=async()=>{if(note){await api(`/proposals/${p.id}/notes`,{method:'POST',body:JSON.stringify({texto:note})});setNote('');api<Proposal>(`/proposals/${p.id}`).then(setFull)}};return <div className="overlay"><aside className="drawer"><button className="close icon" onClick={onClose}><X/></button><p className="eyebrow">Proposta #{p.numero_proposta||p.id}</p><h2>{p.nome}</h2><p>{p.cpf} · {p.telefone}</p><label>Status<select value={p.status} onChange={e=>status(e.target.value)}>{[...new Set([p.status,...stages.map(x=>x.nome),'Pago','Perdido / Cancelado'])].map(s=><option key={s}>{s}</option>)}</select></label><div className="metrics"><span>Troco<b>{money(p.troco)}</b></span><span>Comissão<b>{money(p.comissao)}</b></span><span>Produto<b>{p.produto||'-'}</b></span></div><h3>Anotações</h3><div className="note-form"><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Registrar atualização..."/><button className="primary" onClick={add}>Adicionar</button></div>{(p.notes||[]).map((n:any)=><article className="note" key={n.id}><small>{String(n.data_hora).replace('T',' ')}</small>{n.texto}</article>)}<h3>Histórico</h3>{(p.history||[]).map((h:any)=><article className="history" key={h.id}><b>{h.status_novo}</b><small>{h.observacao}</small></article>)}</aside></div>}
function Today(){const [items,setItems]=useState<Proposal[]>([]);useEffect(()=>api<{items:Proposal[]}>('/proposals?limit=1000').then(x=>setItems(x.items.filter(p=>p.data_retorno===today||(!p.data_retorno&&p.status!=='Pago'&&p.status!=='Perdido / Cancelado')))),[]);return <><Title title="Operação de hoje" subtitle="Priorize retornos, propostas paradas e pendências operacionais."/><div className="stats"><Stat label="Na fila" value={items.length}/><Stat label="Retornos hoje" value={items.filter(x=>x.data_retorno===today).length}/><Stat label="Sem retorno" value={items.filter(x=>!x.data_retorno).length}/></div><ProposalsList items={items}/></>}
function Tasks(){const [items,setItems]=useState<any[]>([]); const [title,setTitle]=useState('');const load=()=>api<any[]>('/tasks').then(setItems);useEffect(load,[]); const add=async(e:React.FormEvent)=>{e.preventDefault();if(title){await api('/tasks',{method:'POST',body:JSON.stringify({titulo:title,data_tarefa:today})});setTitle('');load()}};return <><Title title="Agenda" subtitle="Tarefas e retornos vinculados às propostas."/><form className="quick-add" onSubmit={add}><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Nova tarefa"/><button className="primary">Adicionar</button></form><div className="list">{items.map(x=><article key={x.id}><div><b>{x.titulo}</b><small>{x.categoria} · {x.data_tarefa} {x.proposta_nome&&`· ${x.proposta_nome}`}</small></div><span className="badge">{x.status}</span></article>)}</div></>}
function Simulator(){const [form,setForm]=useState({valor_base:'',margem:'',coeficiente:'0.024088'});const [result,setResult]=useState<any>();const calculate=async(e:React.FormEvent)=>{e.preventDefault();setResult(await api('/simulator/inss',{method:'POST',body:JSON.stringify(form)}))};return <><Title title="Simulador INSS" subtitle="Pré-atendimento por valor desejado ou margem disponível."/><form className="card simulator" onSubmit={calculate}><div className="grid"><label>Valor desejado<input value={form.valor_base} onChange={e=>setForm({...form,valor_base:e.target.value})}/></label><label>Margem disponível<input value={form.margem} onChange={e=>setForm({...form,margem:e.target.value})}/></label><label>Coeficiente<input value={form.coeficiente} onChange={e=>setForm({...form,coeficiente:e.target.value})}/></label></div><button className="primary">Calcular</button>{result&&<div className="stats"><Stat label="Valor estimado" value={money(result.valor_estimado)}/><Stat label="Parcela estimada" value={money(result.parcela_estimada)}/><Stat label="Coeficiente" value={result.coeficiente}/></div>}</form></>}
function Messages(){const [items,setItems]=useState<any[]>([]);const [kind,setKind]=useState('message');const [name,setName]=useState('');const [text,setText]=useState('');const load=()=>api<any[]>(`/templates/${kind}`).then(setItems);useEffect(load,[kind]);const save=async(e:React.FormEvent)=>{e.preventDefault();await api(`/templates/${kind}`,{method:'POST',body:JSON.stringify({nome:name,texto:text,ordem:items.length})});setName('');setText('');load()};return <><Title title="Mensagens" subtitle="Modelos reutilizáveis com variáveis de cliente."/><div className="tabs"><button className={kind==='message'?'selected':''} onClick={()=>setKind('message')}>Modelos da proposta</button><button className={kind==='generator'?'selected':''} onClick={()=>setKind('generator')}>Gerador</button></div><form className="card form" onSubmit={save}><label>Nome<input value={name} onChange={e=>setName(e.target.value)} required/></label><label>Texto<textarea value={text} onChange={e=>setText(e.target.value)} required placeholder="Olá, {nome}..."/></label><button className="primary">Salvar modelo</button></form><div className="list">{items.map(x=><article key={x.nome}><div><b>{x.nome}</b><small>{x.texto}</small></div><button onClick={()=>navigator.clipboard.writeText(x.texto)}>Copiar</button></article>)}</div></>}
function Closed(){const [data,setData]=useState<{columns:Record<string,Proposal[]>}>({columns:{}});const [month,setMonth]=useState(new Date().toISOString().slice(0,7));useEffect(()=>api<typeof data>(`/board?closed=true&mes=${month}`).then(setData),[month]);return <><Title title="Propostas encerradas" subtitle="Exibidas pelo dia real de encerramento, não pela data de criação." action={<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/>}/><div className="closed-grid">{Object.entries(data.columns).filter(([,v])=>v.length).map(([status,items])=><section className="card" key={status}><h3>{status}</h3>{items.map(p=><article className="proposal-line" key={p.id}><b>{p.nome}</b><span>{money(p.comissao)}</span></article>)}</section>)}</div></>}
function Dashboard(){const [data,setData]=useState<any>();const [month,setMonth]=useState(new Date().toISOString().slice(0,7));useEffect(()=>api(`/dashboard?mes=${month}`).then(setData),[month]);return <><Title title="Dashboard" subtitle="Indicadores de produção e encerramento." action={<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/>}/>{data&&<><div className="stats"><Stat label="Propostas criadas" value={data.total}/><Stat label="Pagas" value={data.closed.find((x:any)=>x.status==='Pago')?.total||0}/><Stat label="Perdidas" value={data.closed.find((x:any)=>x.status!=='Pago')?.total||0}/></div><div className="card chart">{data.by_status.map((x:any)=><div key={x.status}><span>{x.status}</span><i style={{width:`${Math.max(5,(x.total/Math.max(1,data.total))*100)}%`}}/><b>{x.total}</b></div>)}</div></>}</>}
function Stages(){const [items,setItems]=useState<Stage[]>([]);const [name,setName]=useState('');const load=()=>api<Stage[]>('/stages').then(setItems);useEffect(load,[]);const add=async(e:React.FormEvent)=>{e.preventDefault();await api('/stages',{method:'POST',body:JSON.stringify({nome:name,ordem:items.length+1})});setName('');load()};return <><Title title="Etapas do funil" subtitle="Edite a ordem e ative/desative colunas sem alterar código."/><form className="quick-add" onSubmit={add}><input value={name} onChange={e=>setName(e.target.value)} placeholder="Nova etapa"/><button className="primary">Adicionar</button></form><div className="list">{items.map(x=><article key={x.id}><b>{x.ordem}. {x.nome}</b><label className="switch"><input type="checkbox" checked={!!x.ativo} onChange={async e=>{await api(`/stages/${x.id}`,{method:'PUT',body:JSON.stringify({...x,ativo:e.target.checked})});load()}}/><span/>Ativa</label></article>)}</div></>}
function ImportExport(){const upload=async(e:React.ChangeEvent<HTMLInputElement>,path:string)=>{const file=e.target.files?.[0];if(!file)return;const form=new FormData();form.append('file',file);const r=await fetch('/api'+path,{method:'POST',body:form});if(!r.ok)alert('Não foi possível processar o arquivo');else alert('Arquivo processado com sucesso')};return <><Title title="Importar e exportar" subtitle="Migração e integração por planilhas, sempre na cópia local."/><div className="action-grid"><section className="card"><h3>Importar propostas</h3><p>CSV ou XLSX com colunas do CRM.</p><input type="file" accept=".csv,.xlsx" onChange={e=>upload(e,'/import')}/></section><section className="card"><h3>Converter contatos</h3><p>Normaliza nome, telefone e CPF.</p><input type="file" accept=".csv" onChange={e=>upload(e,'/contacts/convert')}/></section><section className="card"><h3>Exportar dados</h3><p>Baixe a base de propostas atual.</p><a className="primary" href="/api/export/xlsx">Baixar XLSX</a><a href="/api/export/csv">Baixar CSV</a></section></div></>}
function ProposalsList({items}:{items:Proposal[]}){return <div className="list">{items.map(p=><article key={p.id}><div><b>{p.nome}</b><small>{p.status} · {p.data_retorno||'Sem retorno definido'}</small></div><ChevronRight/></article>)}</div>};function Stat({label,value}:{label:string;value:any}){return <div className="stat"><small>{label}</small><strong>{value}</strong></div>};
createRoot(document.getElementById('root')!).render(<App/>);
